to:
  # Blog Information
  title:        "TimbaObjects Technologies Ltd."
  subtitle:     "...delivering great applications to a mobile device near you"
  cover_image:  blog-cover.jpg
  logo:         logo.png
  home-cover:   home-bg.jpg
  cover:        about-cover.png
  contact-cover:  contact.jpg
  br-one:        br.png
  br-two:        br_2.png
  br-three:      br_3.png
  ap-results:   apollo-results.png
  ap-pp:        apollo-pp.png
  ap-chk:       apollo-checklist.png
  ap-pst:       apollo-posts.png
  ap-dash:      apollo-dashboard.png
  face:         facebook.png
  
  # Company information
  company:      TimbaObjects
  url:          http://timbaobjects.com/
  facebook:     timbaobjects
  twitter:      timbaobjects
  gplus:        '114364617810690415019'
  blog_link:    '/blog/'
  about_link:   '/about/'
  contact_link: '/contact/'
  
  # Product Information
  portfolio_link: '/portfolio/'
  tagline:      ""
  apollo-link:     '/apollo/'
  br-link:     '/br/'

  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  true
  
  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false
    
  
 # Analytics     
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html
      
      
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://timbaobjects.com
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter:    pygments

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 4

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false